### ISSUE TITLE
Version number should be removed for unpkg.com to properly work

### ISSUE THREAD

**Issue by exside** [DanZiti/GrindstoneJS#4]
I tried to pull in grindstone from unpkg.com like this:

```html
<script src="https://unpkg.com/grindstone@latest/dist/grindstone.js"></script>
```
which fails because the file is named ```grindstone_v3.1.1.js``` instead of ```grindstone.js```

if you compare how vue.js does this for example, you'll see the problem:

```html
<script src="https://unpkg.com/vue@latest/dist/vue.js"></script>
```
will work, because the file in dist does not contain any version number

any possibility to change that?

**Comment by dzervoudakes** [comment]
Done :)

**Comment by exside** [comment]
awesome, thanks!
