### ISSUE TITLE
$.ajax() does not seem to deal properly with JSON data

### ISSUE THREAD

**Issue by exside** [DanZiti/GrindstoneJS#5]
Even when the API returns contentType = application/json I need to parse the response with JSON.parse to be able to access it. From jQuery I'm used to specify a dataType property for the $.ajax() method.

**Comment by dzervoudakes** [comment]
Figured this out; I was ignorant of "xhr.responseType" ... if you git checkout the "topic-ajax" branch, you can see the update - now you can add a "dataType" option in your $.ajax options.

Let me know if this works for you before I merge the change into master and bump the fix version :)

**Comment by dzervoudakes** [comment]
Pretty sure this is taken care of, after plenty of testing.  The data in our response is matching the dataType I'm telling it to in the tests.

Please let me know if you experience any other issues.

**Comment by exside** [comment]
Sorry, was busy this week with work =), playing with grindstone for some petprojects, might be able to test it out this weekend, thanks anyways for the fast replies and fixes!!

**Comment by dzervoudakes** [comment]
No worries ... FYI I'm going to be busy myself coming up with the holidays and everything approaching, but I'll continue to respond as quickly as I can if more issues arise.  Thanks gain for taking an interest and helping improve the library :)
